In [2]:
# importing the required liabraries 
from bs4 import BeautifulSoup
import requests

In [3]:
page = requests.get('https://www.unitedhealthgroup.com/')

In [4]:
page

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [8]:
import pandas as pd
d=pd.read_excel("C:\\Users\\Jay kumar yadav\\OneDrive\\Desktop\\Conditional Formatting.xlsx")
df=pd.DataFrame(d)

In [9]:
print(df)

   Conditional Formatting Fun!  Unnamed: 1  Unnamed: 2         Unnamed: 3  \
0                          NaN         NaN         NaN                NaN
1                  Test Scores         NaN         NaN  Restaurant Review
2                         John        95.0         NaN         Customer 1
3                        Kevin        81.0         NaN         Customer 2
4                       Sophia        76.0         NaN         Customer 3
5                         Adam        89.0         NaN         Customer 4
6                       Meghan        92.0         NaN         Customer 5
7                       Annice        65.0         NaN         Customer 6
8                        Debra        51.0         NaN         Customer 7
9                      Michael        92.0         NaN         Customer 8
10                         Tim        81.0         NaN         Customer 9
11                     Garrett        79.0         NaN        Customer 10
12                       Jacob        92.0         NaN        Customer 11
13                      Denice        93.0         NaN                NaN
14                        Eric        88.0         NaN                NaN
15                       James        81.0         NaN                NaN
16                        Paul        70.0         NaN                NaN

             Unnamed: 4                                  Unnamed: 5  \
0                   NaN                                         NaN
1        Date Submitted                                      Review
2   2023-11-28 00:00:00     Great food, will definitely come again!
3   2023-11-18 00:00:00  OK, I wish they filled my water more often
4   2023-10-23 00:00:00      The chicken didn't taste like chicken.
5   2023-10-25 00:00:00                     They double charged me!
6   2023-10-29 00:00:00             Great service, will come again.
7   2023-10-14 00:00:00                    Pricey for what you get.
8   2023-11-01 00:00:00          The steak required lots of chewing
9   2023-11-22 00:00:00           Good entertainment during dinner.
10  2023-11-19 00:00:00                        Loved the appetizer!
11  2023-10-23 00:00:00                            Will come again.
12  2023-11-06 00:00:00                        Will not come again.
13                  NaN                                         NaN
14                  NaN                                         NaN
15                  NaN                                         NaN
16                  NaN                                         NaN

    Unnamed: 6        Unnamed: 7
0          NaN               NaN
1          NaN          Students
2          NaN        Kevin Shah
3          NaN        Tim Briggs
4          NaN     Michael Smith
5          NaN     Debra Collins
6          NaN     Steve Jackson
7          NaN        Kevin Shah
8          NaN         Tim Smith
9          NaN        Kerry West
10         NaN    Jimbo Bradford
11         NaN  Garrett McDonald
12         NaN        Ruby Sloan
13         NaN        Kerry West
14         NaN               NaN
15         NaN               NaN
16         NaN               NaN

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/Dsdata/master/Telecom_customer_churn.csv')
df
# ad k place pa ap kucg v likh sakta h df v likh sakta h

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/Dsdata/master/Telecom_customer_churn.csv')
df
# ad k place pa ap kucg v likh sakta h df v likh sakta h

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
df = pd.read_csv('https://github.com/dsrscientist/dataset4/blob/main/Grades.csv')
df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 35, saw 8